CREATE TABLE countries (
  id SERIAL PRIMARY KEY,
  country_name TEXT NOT NULL,
  flag_emoji TEXT,
  region TEXT,
  tier INTEGER,
  priority_action TEXT,
  cd_name TEXT,
  cd_tenure TEXT,
  mentor_count INTEGER,
  fy25_actual INTEGER,
  fy26_target INTEGER,
  mission_align INTEGER,
  socio_density INTEGER,
  volume_potential INTEGER,
  digital_readiness INTEGER,
  market_score NUMERIC,
  cd_strength INTEGER,
  program_standardization INTEGER,
  legal_entity INTEGER,
  political_risk INTEGER,
  ops_score NUMERIC,
  total_score NUMERIC,
  what_working TEXT,
  what_not_working TEXT,
  growth_ceiling TEXT,
  key_risk TEXT,
  recommendation TEXT,
  iso_code TEXT,
  latitude NUMERIC,
  longitude NUMERIC
);

CREATE TABLE partner_opportunities (
  id SERIAL PRIMARY KEY,
  country_id INTEGER REFERENCES countries(id),
  country_name TEXT,
  organization TEXT,
  org_type TEXT,
  why_fit TEXT,
  partner_type TEXT,
  priority TEXT,
  specific_action TEXT
);
